from  tkinter import *

master = Tk()
Label(master, text='First Name').grid(row=0)
Label(master, text='Last Name').grid(row=1)
Label(master, text='Phone No').grid(row=2)
Label(master, text='Email id').grid(row=3)
Label(master, text='Address').grid(row=4)
var1 =IntVar()
var2 =IntVar()
var3 =IntVar()
var4 =IntVar()

Checkbutton(master,text='Python',variable=var1).grid(row=5,column =1)
Checkbutton(master,text='Networking',variable=var2).grid(row=5,column =2)
Checkbutton(master,text='C++',variable=var3).grid(row=5,column =3)
Checkbutton(master,text='C',variable=var4).grid(row=5, column =4 )
top = Tk()
top.title('Scroll')
Lb = Listbox(top)
Lb.insert(1,"Python")
Lb.insert(2,"Linux")
Lb.insert(3,"Ethical hacking")
Lb.insert(4,"Networking")
Lb.pack()

e1 = Entry(master)
e2 = Entry(master)
e3 = Entry(master)
e4 = Entry(master)
e5 = Entry(master)
e1.grid(row=0,column=1)
e2.grid(row=1,column=1)
e3.grid(row=2,column=1)
e4.grid(row=3,column=1)
e5.grid(row=4,column=1)
mainloop()